{{- $fullName := include "guestbook.fullname" . -}}
{{- $labels := include "guestbook.labels" . | nindent 4}}
{{- $selectorLabels := include "guestbook.selectorLabels" . | nindent 6}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-backend
  labels:
  {{- $labels }}
    app.service: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
    {{- $selectorLabels }}
      app.service: backend
  template:
    metadata:
      labels:
      {{- $labels | indent 4}}
        app.service: backend
    spec:
      containers:
      - name: {{ .Chart.Name }}-backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.port }}
          protocol: TCP
        env:
        - name: PORT
          value: "{{ .Values.backend.service.port }}"
        - name: GUESTBOOK_DB_ADDR
          value: "{{ .Values.backend.dbUrl }}"