---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: guestbook
  namespace: development
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/tag.frontend: glob:*
    filter.fluxcd.io/tag.backend: glob:*
spec:
  releaseName: guestbook
  chart:
    git: git@github.com:chukaofili/gitops-infra
    path: flux_config/charts/guestbook
    ref: master
  values:
    frontend:
      image:
        repository: gcr.io/ms-clients-2018/nodejs-guestbook-frontend
        tag: 0b47b75
      replicaCount: 1
    backend:
      dbUrl: "mongodb.system:27017"
      image:
        repository: gcr.io/ms-clients-2018/nodejs-guestbook-backend
        tag: 0b47b75
      replicaCount: 1
